name: CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
env:
  GO111MODULE: on
  GOPROXY: "https://proxy.golang.org"
  
jobs:
  test:
    name: Test
    strategy:
      matrix:
        go: ['1.22.x', '1.24.x']
        platform: [ubuntu-latest] # can not run in windows OS
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
        cache: false

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Cache go modules
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.vars.outputs.GO_CACHE }}
          ~/go/pkg/mod
        key: ${{ runner.os }}-${{ matrix.go-version }}-go-ci-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.go-version }}-go-ci-

    - name: Unit test
      run: go test -v -cover .
